network:
  version: 2
  wifis:
    NM-bc669d76-6fc1-4d88-a0f1-97bd018c9f18:
      renderer: NetworkManager
      match:
        name: "wlan0"
      dhcp4: true
      dhcp6: false
      access-points:
        "TP-Link_3682":
          auth:
            key-management: "psk"
            password: "mhleenetmhlee"
          networkmanager:
            uuid: "bc669d76-6fc1-4d88-a0f1-97bd018c9f18"
            name: "TP-Link_3682"
            passthrough:
              wifi-security.auth-alg: "open"
              ipv6.addr-gen-mode: "default"
              ipv6.ip6-privacy: "-1"
              proxy._: ""
      networkmanager:
        uuid: "bc669d76-6fc1-4d88-a0f1-97bd018c9f18"
        name: "TP-Link_3682"
